name: 'TF Action'
description: 'Assists in running various tf workflows from GitHub Actions.'
inputs:
  # REQUIRED
  tf_flavor:
    description: 'Which flavor of tf infra-as-code to use; `tofu` or `terraform`'
    type: string
    required: true
  dir_path:
    description: 'Path relative to root of repo for working tf dir.'
    type: string
    required: true
  version:
    description: 'Version of the tf executable to install.'
    type: string
    required: true
  plan_only: 
    description: 'Boolean for whether to only plan and not apply.'
    type: boolean
    required: true
  # OPTIONAL
  init_args:
    description: '[Optional] Additional command line args. Useful for --backend-config and ephemeral or dynamic deploys.'
    type: string
    required: false
    default: ''
  plan_args: 
    description: '[Optional] Additional command line args. Useful for --var-file and ephemeral or dynamic deploys.'
    type: string
    required: false
    default: ''
  plan_artifact_name:
    description: '[Optional] Artifact name for plan file to use. If passed, then we jump straight to apply.'
    type: string
    required: false
    default: ''
outputs:
  tf_output:
    description: 'tf outputs in -json format.'
    value: ${{ steps.apply.outputs.tf_output }}
  plan_artifact_name: 
    description: 'Name of the relevant tf plan artifact, either produced, consumed, or both.'
    value: ${{ steps.artifact-name.outputs.plan_artifact_name }}
runs:
  using: 'composite'
  steps:
  - name: Validate inputs
    if: ${{ inputs.tf_flavor != 'tofu' && inputs.tf_flavor != 'terraform' }}
    shell: bash
    run: |
      echo "::error file='jamcatbiz/do-tf/action.yml',line=56,endLine=56,title='Invalid Input tf_flavor'::'Valid values for tf_flavor include tofu and terraform."
      exit 1
  - uses: actions/checkout@v4
  - uses: opentofu/setup-opentofu@v1
    if: ${{ inputs.tf_flavor == 'tofu' }}
    with:
      tofu_version: ${{ inputs.version }}
      tofu_wrapper: false
  - uses: hashicorp/setup-terraform@v3
    if: ${{ inputs.tf_flavor == 'terraform' }}
    with:
      terraform_version: ${{ inputs.version }}
      terraform_wrapper: false
  - name: Do tf plan workflow
    id: plan
    if: ${{ inputs.plan_artifact_name == '' }}
    shell: bash
    run: |
      cd ${{ inputs.dir_path }}
      ${{ inputs.tf_flavor }} fmt -check -recursive
      ${{ inputs.tf_flavor }} init -input=false ${{ inputs.init_args }}
      ${{ inputs.tf_flavor }} validate -no-color
      ${{ inputs.tf_flavor }} plan -no-color -input=false -out=tfplan ${{ inputs.plan_args }}
      ${{ inputs.tf_flavor }} show -no-color tfplan > tf.txt
      {
        echo "##### $(cat tf.txt | grep --color=never -E '^[[:punct:]]|Plan')"
        echo "<details><summary>:mag: Show Plan</summary>"
        echo ""
        echo "\`\`\`hcl"
        echo "$(cat tf.txt)"
        echo "\`\`\`"
        echo "</details>"
      } >> $GITHUB_STEP_SUMMARY
  - name: Determine artifact name
    id: artifact-name
    shell: bash
    run: |
      echo 'plan_artifact_name=${{ inputs.plan_artifact_name != '' && inputs.plan_artifact_name || format('{0}-tfplan', hashFiles(format('{0}/tfplan', inputs.dir_path))) }}' >> $GITHUB_OUTPUT
  - uses: actions/upload-artifact@v4
    if: ${{ inputs.plan_artifact_name == '' }}
    with:
      name: ${{ steps.artifact-name.outputs.plan_artifact_name }}
      path: ${{ inputs.dir_path }}/tfplan
      retention-days: 7
  - uses: actions/download-artifact@v4
    if: ${{ inputs.plan_only == 'false' }}
    with:
      name: ${{ steps.artifact-name.outputs.plan_artifact_name }}
      path: ${{ inputs.dir_path }}
  - name: Do tf apply workflow
    id: apply
    if: ${{ inputs.plan_only == 'false' }}
    shell: bash
    run: |
      cd ${{ inputs.dir_path }}
      ${{ inputs.tf_flavor }} apply -no-color -input=false "${{ steps.artifact-name.outputs.plan_artifact_name }}"
      {
        echo 'tf_output<<EOF'
        echo $(${{ inputs.tf_flavor }} output -json)
        echo 'EOF'
      } >> $GITHUB_OUTPUT
      {
        echo "|Name|Value|"
        echo "|:-:|:-:|"
        echo "$(${{ inputs.tf_flavor }} output -json | jq -r 'keys[] as $k | "|\`\($k)\`|\`\(.[$k].value)\`|"')"
      } >> $GITHUB_STEP_SUMMARY